// MAX DISTANCE THRESHOLD
export const MAX_DISTANCE = 5; // TODO CAN BE LOADED FROM ENV

export const DRIVER_STATUS = {
    AVAILABLE: "AVAILABLE",
    NOTAVAILABLE:"NOT-AVAILABLE",
    ACTIVE:"ACTIVE",
    INACTIVE:"IN-ACTIVE"
}
